---
repository: sp0rk/sp0rk.github.io
version: 2
darkmode: never

name: Julian Jurec
title: Android Developer
email: julian.jurec@gmail.com

github_username: sp0rk
stackoverflow_username: "4961317"
instagram_username: sp0rque
linkedin_username: julianjurec
additional_links:
  - title: Resume PDF download
    icon: far fa-file-pdf
    url: https://github.com/sp0rk/sp0rk.github.io/raw/pdf/julian_jurec_resume.pdf

# --------------------------------------------------------------------------------------------------------------------------------------

about_content: |
  (TODO)

# --------------------------------------------------------------------------------------------------------------------------------------

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: (TODO)
        quote: >
          (TODO)
        description: |
          (TODO)

# --------------------------------------------------------------------------------------------------------------------------------------

  - title: Experience
    layout: list
    content:
      - layout: top-middle
        title: Applover
        sub_title: Android Developer
        caption: 2017 - Present
        quote: >
          (TODO)
        description: |
          I watched and helped Applover grow from a team of a dozen to around 150 people. Apart from working with a number of clients on various projects I worked on designing, implementing, and maintaining multiple processes used in day-to-day work, including:
          - Software development processes - git workflow, automation, quality metrics and requirements, analytics, definition of done, release checklist, etc.
          - Pre-development project processing - requirements discovery, system design workshops, specification crafting, team onboarding, kickoff checklist, etc.
          - Developer recruitment process (TODO)

          A selection of noteworthy projects I've been involved with can be found listed under the Projects section of this resume.

      - layout: top-middle
        title: Applover
        sub_title: Android Team Lead
        caption: (TODO)
        quote: >
          (TODO)
        description: |
          (TODO)

      - layout: top-middle
        title: Applover
        sub_title: Business analyst
        caption: (TODO)
        quote: >
          (TODO)
        description: |
          (TODO)

      - layout: top-middle
        title: Software Development Academy
        sub_title: Teacher
        caption: (TODO)
        quote: >
          (TODO)
        description: |
          (TODO)

      - layout: top-middle
        title: GSM Billing Ltd.
        sub_title: Mobile developer
        caption: 2016 - 2017
        quote: >
          Working with Java, Retrofit, Butterknife, Gradle, Retrofit, Swift, Objective-C, Cocoapods, Alamofire, Parse.com
        description: |
          I developed a number of small internal apps for a British tele-comms company. We worked in a 4-person cross-platform team and cooperated with an offshore backend team. I learned a lot, picked my favourite platform to go forward and moved on during tech department restructuring.

# --------------------------------------------------------------------------------------------------------------------------------------

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Wrocław University of Science and Technology
        caption: 2015 - 2019
        sub_title: Faculty of Computer Science and Management
        quote: >
          BEng Computer Science

# --------------------------------------------------------------------------------------------------------------------------------------

  - title: Out of office
    layout: text
    content: |
      Out of work I'm mostly into:
      - Rock climbing
      - Nature Photography
      - No Limit Texas Hold'em poker
      - Jazz

# --------------------------------------------------------------------------------------------------------------------------------------

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

# --------------------------------------------------------------------------------------------------------------------------------------
