---
repository: sp0rk/sp0rk.github.io
version: 2
darkmode: never

name: Julian Jurec
title: Android Developer
email: julian.jurec@gmail.com

github_username: sp0rk
stackoverflow_username: "4961317"
instagram_username: sp0rque
linkedin_username: julianjurec
additional_links:
  - title: Resume PDF download
    icon: far fa-file-pdf
    url: https://github.com/sp0rk/sp0rk.github.io/raw/pdf/julian_jurec_resume.pdf

# --------------------------------------------------------------------------------------------------------------------------------------

about_title: Into
about_content: |
  (TODO)

# --------------------------------------------------------------------------------------------------------------------------------------

content:
  - title: Experience
    layout: list
    content:
      - layout: top-middle
        title: Applover
        sub_title: Android Developer
        caption: 2017 - Present
        quote: >
          Watched and helped Applover grow from a team of a dozen to around 150 people
        description: |
          Apart from working with a number of clients on various projects I worked on designing, implementing, and maintaining multiple processes used in day-to-day work, including:
          - Software development processes - git workflow, automation, quality metrics and requirements, analytics, definition of done, release checklist, etc.
          - Pre-development project processing - requirements discovery, system design workshops, specification crafting, team onboarding, kickoff checklist, etc.
          - Developer recruitment process - role requirements, 2-stage interview, loop meetings, tech onboarding

          A selection of noteworthy projects I've been involved with can be found listed under the Projects section of this resume

      - layout: top-middle
        title: Applover
        sub_title: Android Team Lead
        caption: 2019 - Present
        quote: >
          I led the 5-7 person Android Team in Applover and helped build the Flutter team around one of the teammates
        description: |
          - Conducted most of the interviews for new candidates
          - Helped coordinate and divide work between developers, advising on project assignments
          - Fostered a friendly and productive atmosphere and working conditions in the team
          - Led tech stack innovations and automation tools implementation
          - Handled numerous project specifications, estimates and design workshops

      - layout: top-middle
        title: Applover
        sub_title: Business analyst
        caption: 2022 - Present
        quote: >
          I was asked to dedicate some time to share my tech-focused perspective with our BA team to deliver new value to the clients
        description: |
          - Participated in sales calls as a tech expert
          - Helped define business requirements and suggested tech solutions to fulfill them
          - Provided ballpark estimates
          - Conducted tech audits of existing products and market research for competition and potential improvements

      - layout: top-middle
        title: Software Development Academy
        sub_title: Teacher
        caption: 2017 - 2019
        quote: >
          Taught Java and Python classes in both Polish and English
        description: |
          - Specialised in the introductory sections as it felt most rewarding to me
          - Conducted shell+git proficiency workshops
          - Helped expand the offering to the Baltics by leading the way in the Estonian branch
          - A significant number of my students are now successful developers, working in IT for years

      - layout: top-middle
        title: GSM Billing Ltd.
        sub_title: Mobile developer
        caption: 2016 - 2017
        description: |
          - Developed a number of small internal apps for a British tele-comms company
          - Worked in a 4-person cross-platform team and cooperated with an offshore backend team
          - Learned a lot, picked my favourite platform to go forward and moved on during tech department restructuring

# --------------------------------------------------------------------------------------------------------------------------------------

  - title: Some noteworthy projects
    layout: list
    content:
      - layout: top-middle
        title: (TODO)
        quote: >
          (TODO)
        description: |
          (TODO)

# --------------------------------------------------------------------------------------------------------------------------------------

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Wrocław University of Science and Technology
        caption: 2015 - 2019
        sub_title: Faculty of Computer Science and Management
        quote: >
          BEng Computer Science

# --------------------------------------------------------------------------------------------------------------------------------------

  - title: Out of office
    layout: text
    content: |
      Out of work I'm mostly into:
      - Rock climbing
      - Nature Photography
      - No Limit Texas Hold'em poker
      - Jazz

# --------------------------------------------------------------------------------------------------------------------------------------

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

# --------------------------------------------------------------------------------------------------------------------------------------

footer_show_references: true
references_title: Last updated 2023-03-24. For up-to-date version visit sp0rk.github.io
