---
repository: sp0rk/sp0rk.github.io
version: 2
darkmode: never

name: Julian Jurec
title: Software Consultant
email: julian.jurec@gmail.com

github_username: sp0rk
linkedin_username: julianjurec
additional_links:
  - title: Resume PDF download
    icon: far fa-file-pdf
    url: https://github.com/sp0rk/sp0rk.github.io/raw/pdf/julian_jurec_resume.pdf

# --------------------------------------------------------------------------------------------------------------------------------------

about_title: Intro
about_content: |
  I've worked as a software consultant since 2016. My role varied, from solely coding to business analysis to leadership.
  I've been involved in well over 20 projects of varying sizes, scopes, and domains over the years. 

# --------------------------------------------------------------------------------------------------------------------------------------

content:
  - title: Jobs
    layout: list
    content:
      - layout: top-middle
        title: Loomis Pay
        sub_title: Android developer (2023 - Now)
        description: |
          - Built Loomis Teller - a green-field payment facilitator app, connecting multiple payment providers with multiple integrations. 
          - Maintained beautiful partner integration documentation: RS232/USB, MDB, Local HTTP server, app2app, Cloud.
          - Worked in PCI DSS compliant environment
      - layout: top-middle
        sub_title: Product Owner (2025 - Now)
        description: |
          - Owned Loomis Teller, made decisions, prioritised, externally represented the product
          - Guided development team by managing backlog and communicating with stakeholders 

      - layout: top-middle
        title: DNA Technology
        sub_title: Software Consultant (2023 - Now)
        description: |
          - Worked with DNA's clients, growing the relationships while caring for DNA's internal environment.
      - layout: top-middle
        sub_title: Team Lead (2025 - Now)
        description: |
          - Facilitated growth and well-being for several team members

      - layout: top-middle
        title: Applover
        sub_title: Android developer (2017 - 2023)
        description: |
          - Developed modern, maintainable, scalable green-field code.
          - Supported and maintaned massive legacy codebases.
          - Supported numerous clients in design, implementation, and maintenance of their software products.
          - Built processes and metrics to improve their way of work.
      - layout: top-middle
        sub_title: Android team lead (2019 - 2023)
        description: |
          - Helped grow Applover from ~10 to ~150 people
          - Cared for a team of 5-10 in their growth and well-being
          - Led recruitment
          - Led org-wide tech decisions
      - layout: top-middle
        sub_title: Business analyst (2022 - 2023)
        description: |
          - Had sales meetings as a tech expert
          - Defined business requirements, built processes in the clients' environments
          - Estimated, audited, conducted market research

      - layout: top-middle
        title: Software Development Academy
        sub_title: Coding teacher (2017 - 2019)
        description: |
          - Taught Java and Python classes in both Polish and English
          - Conducted shell+git proficiency workshops
          - Helped expand the offering to the Baltics by leading the way in the Estonian branch

      - layout: top-middle
        title: GSM Billing Ltd.
        sub_title: Mobile developer (2016 - 2017)
        description: |
          - Developed internal tools for a British tele-comms company in a small cross-platform team

# --------------------------------------------------------------------------------------------------------------------------------------

  - title: Projects
    layout: text
    content: |
      ## Loomis Teller
      - Built green-field payment facilitator app, connecting multiple payment providers with multiple integrations: RS232, MDB, Local HTTP server and others.

      ## Glovo
      - Designed a cross-platform, dynamic, backend-driven, recursive support tree in a food delivery app

      ## Bodycoach
      - Ported design-award winning iOS app to Android with fully custom UI and animations.

      ## Razer
      - Worked on Razer Phone's official camer app. Performance-testing, low-level Android code, Canvas-based UI.

      ## Plenty of Fish
      - Led a total rebrand in a massive, legacy codebase with A/B-test-based staged rollout

# --------------------------------------------------------------------------------------------------------------------------------------

  - title: Skills
    layout: text
    content: |
      ## Preferred Android tech stack:
      - Kotlin, Coroutines, Flows, Room, Dagger/Hilt, Compose, MVVM, Clean arch.

      ## Also Fluent in:
      - Java, Python, JS, sh, most Android tools/patterns popular since 2015.
      - AWS, GitLab CI/CD, Github Actions, Gradle Plugin development and pipeline optimisation
      - System architecture design, process development, backlog management
      - Leadership, business analysis, technical writing, client/stakeholder comms.
      - Teaching, mentoring, public speaking & presenting,

      ## Languages:
      - Proficient Polish and English

# --------------------------------------------------------------------------------------------------------------------------------------

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Wrocław University of Science and Technology
        caption: Faculty of Computer Science and Management (2015 - 2019)
        sub_title: BEng Computer Science - thesis on convolutional neural networks

# --------------------------------------------------------------------------------------------------------------------------------------

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

# --------------------------------------------------------------------------------------------------------------------------------------

footer_show_references: true
references_title: Last updated 2026-01-30. For up-to-date version visit sp0rk.github.io
