---
name: Deploy Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  actionsLint:
    name: Actions Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Github Actions
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check
          fail_on_error: true

  yamlLint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check YAML
        uses: reviewdog/action-yamllint@v1
        with:
          reporter: github-check
          fail_on_error: true

  languageLint:
    name: Language Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check insensitive language
        uses: reviewdog/action-alex@v1
        with:
          reporter: github-check
          fail_on_error: true

  englishLint:
    name: English Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check spelling
        uses: reviewdog/action-misspell@v1
        with:
          reporter: github-check
          fail_on_error: true
          locale: "UK"
          path: |
            _data

  deploy:
    name: Deploy
    needs: [actionsLint, languageLint, yamlLint, englishLint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          target-folder: docs

  buildPdf:
    name: Build PDF
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Convert HTML to PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: index.html
          outputFile: julian_jurec_resume.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - name: Upload PDF
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'julian_jurec_resume.pdf'
