name: Deploy Pages

on:
  push:
    branches:
      - main 

jobs:
  actionsLint:
    name: Actions Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Github Actions
        uses: reviewdog/action-actionlint@v1
        with: 
          reporter: github-check
          fail_on_error: true

  languageLint:
    name: Language Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check insensitive language
        uses: reviewdog/action-alex@v1
        with: 
          reporter: github-check
          fail_on_error: true

  englishLint:
    name: English Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check language
        uses: reviewdog/action-languagetool@v1
        with:
            reporter: github-check
            failOnError: true

  deploy:
    needs: [actionsLint, languageLint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          target-folder: docs
